# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hash.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nhash.proto\"\x1b\n\x0bHashRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1c\n\x0cHashResponse\x12\x0c\n\x04hash\x18\x01 \x01(\x0c\x32\x33\n\x06Hasher\x12)\n\x06HashMe\x12\x0c.HashRequest\x1a\r.HashResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hash_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HASHREQUEST']._serialized_start=14
  _globals['_HASHREQUEST']._serialized_end=41
  _globals['_HASHRESPONSE']._serialized_start=43
  _globals['_HASHRESPONSE']._serialized_end=71
  _globals['_HASHER']._serialized_start=73
  _globals['_HASHER']._serialized_end=124
# @@protoc_insertion_point(module_scope)
